/** @type {import('tailwindcss').Config} */
module.exports = {
	content: [
		'./*.php',
		'./inc/**/*.php',
		'./templates/**/*.php',
		'./template-parts/**/*.php',
	],
	theme: {
		extend: {
			colors: {
				navy: '#1a1d2e',
				'royal-blue': '#2563eb',
				'accent-yellow': '#ffcc00',
			},
			fontFamily: {
				assistant: ['Assistant', 'ui-sans-serif', 'system-ui', 'sans-serif'],
			},
		},
	},
	plugins: [
		require('@tailwindcss/typography'),
		require('@tailwindcss/forms'),
	],
	safelist: [
		'wpcf7',
		'wpcf7-form',
		'wpcf7-form-control-wrap',
		'wpcf7-form-control',
		'wpcf7-select',
		'wpcf7-submit',
		'wpcf7-spinner',
		'wpcf7-response-output',
		'wpcf7-validation-errors',
		'wpcf7-mail-sent-ok',
		'wpcf7-not-valid',
		'wpcf7-not-valid-tip',
		'btn-send',
		'lead-form-wrapper',
		'form-title',
		'sb-blue-gradient',
		'site-header--transparent',
		'site-header--solid',
		'hero--transparent-header',
		'hero-overlay--full',
		'sb-midrag',
		'sb-midrag__logo',
		'sb-midrag__rating',
		'sb-midrag__stars',
		'sb-midrag__meta',
		'sb-midrag__score',
		'sb-midrag__text',
		'sb-midrag__label',
		'sb-midrag__reviews',
		'sb-footer-info',
		'sb-footer-info__item',
		'sb-footer-info__link',
		'sb-footer-info__icon',
		'sb-footer-info__svg',
		'sb-footer-info__body',
		'sb-footer-info__title',
		'sb-footer-info__subtitle',
		'site-branding',
		'site-branding__logo',
		'site-branding__name',
		'site-branding__mark-wrap',
		'site-branding__mark',
		'site-branding__mark--image',
		'site-branding__mark--transparent-state',
		'site-branding__mark--scrolled-state',
		'site-branding__mark--logo',
		'site-branding__mark--fallback',
		'site-branding__text',
		'site-branding__title',
		'site-branding__tagline',
		'testimonials-slider',
		'testimonials-slider__mask',
		'testimonials-slider__track',
		'testimonials-slider__group',
		'testimonial-card',
	],
};
